version: '2'
services:
    locadora-app:
        image: locadora
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://locadora-postgresql:5432/locadora
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    locadora-postgresql:
        extends:
            file: postgresql.yml
            service: locadora-postgresql
